//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataget
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class khwabEntities : DbContext
    {
        public khwabEntities()
            : base("name=khwabEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<mcq> mcqs { get; set; }
        public DbSet<Paper> Papers { get; set; }
        public DbSet<student> students { get; set; }
        public DbSet<user> users { get; set; }
    }
}
